FROM openjdk:11.0.8-slim-buster
MAINTAINER john.a.sexton@gmail.com
RUN apt-get update -q \
    && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
      curl \
      wget \
      vim
